server:
  port: 8080
  servlet:
    context-path: /security
  shutdown: graceful

spring:
  application:
    name: spring-jwt-security
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    name: jpa-pg-datasource
    url: 'jdbc:postgresql://localhost:5432/spring_security_db'
    username: postgres
    password: Password@1
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update # Hibernate ddl auto (create, create-drop, validate, update)
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  main:
    banner-mode: off
  mail:
    default-encoding: UTF-8
    host: smtp.mailtrap.io
    username: ba82994703feaa
    password: ea2c03a9a0d824
    port: 2525
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false

    template:
      confirm-account: account-confirmation-template
      reset-password: reset-password-template
    subject:
      confirm-account: Account confirmation on Chrisgya Site
      reset-password: Password reset on Chrisgya Site


management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
  flyway:
    enabled: false
    schemas: bp
    user: postgres
    password: Password@1

  file:
    directory: C://temp/${spring.application.name}
    image-extensions: jpg, jpeg, png

app:
  security:
    jwt:
      keystore-location: keys/keystore_chrisgya.jks
      keystore-password: Password@1
      key-alias: chrisgyaspsec
      private-key-passphrase: Password@1
      bycriptStrength: 12
      tokenExpirationAfterSeconds: 1440  #24 hours or 1 day
      refresh-token-expires-after-seconds: 10080  #7 day
      activation-token-expiration-after-seconds: 10080  #7 day
      tokenPrefix: 'Bearer '
      issuer: chrisgya

custom-thread:
  core-pool-size: 4
  max-pool-size: 10
  queue-capacity: 100

front-end-url:
  base-url: http://localhost:3000
  confirm-account: http://localhost:3000/verify-account/
  reset-password: http://localhost:3000/reset-password/